"""
Example Usage: Loading Generated Dataset and Rendering Images

This script demonstrates how to load the dataset generated by generator_working.py
and render images/visualizations from the stored trajectory data.
"""

import pickle
import gzip
import numpy as np
import matplotlib.pyplot as plt
from multigrid.envs.goal_prediction import AGREnv


def load_dataset(filepath):
    """Load the pickled dataset."""
    print(f"Loading dataset from {filepath}...")
    with gzip.open(filepath, 'rb') as f:
        results = pickle.load(f)  # type: ignore
    print(f"✅ Loaded {len(results)} scenarios")
    return results


def render_trajectory_images(scenario, tile_size=32, save_path=None):
    """
    Render all images for a trajectory.
    
    Args:
        scenario: A scenario dict from the dataset
        tile_size: Size of each grid tile in pixels (default: 32)
        save_path: Optional path to save images (e.g., "trajectory_images/img_{step}.png")
    
    Returns:
        List of rendered images (numpy arrays)
    """
    # Reconstruct the environment
    # Note: AGREnv expects lists, not dicts for start positions
    start_pos_list = [(0, 0), tuple(scenario['start_positions'])]  # Observer, then target
    start_dir_list = [0, scenario['start_directions']]  # Observer, then target
    
    env = AGREnv(
        size=scenario['size'],
        base_grid=scenario['base_grid'],
        goals=scenario['goals'],
        goal=scenario['goal'],
        agents_start_pos=start_pos_list,
        agents_start_dir=start_dir_list
    )
    
    obs, info = env.reset()
    images = []
    
    print(f"Rendering trajectory with {len(scenario['all_actions'])} steps...")
    
    for step_idx, action in enumerate(scenario['all_actions']):
        # Render the current state (only show target agent, not observer)
        img = env.grid.render(
            tile_size=tile_size,
            agents=env.unwrapped.agents[1:],  # Only target agent  # type: ignore
            highlight_mask=None
        )
        images.append(img)
        
        # Save image if path provided
        if save_path:
            filename = save_path.format(step=step_idx)
            plt.imsave(filename, img)
        
        # Execute action
        actions = {0: 3, 1: action}  # Observer stays still, target moves
        obs, _, _, _, _ = env.step(actions)
    
    env.close()
    print(f"✅ Rendered {len(images)} images")
    return images


def display_trajectory_summary(scenario):
    """Display summary information about a trajectory."""
    print("\n" + "="*60)
    print("TRAJECTORY SUMMARY")
    print("="*60)
    print(f"Grid Size: {scenario['size']}x{scenario['size']}")
    print(f"Layout ID: {scenario['layout_id']}")
    print(f"Scenario ID: {scenario['scenario_id']}")
    print(f"Initial Distance: {scenario['initial_distance']}")
    
    style_names = ["like_wall", "hate_wall", "like_edge", "hate_edge"]
    print(f"Hidden Cost Type: {scenario['hidden_cost_type']} ({style_names[scenario['hidden_cost_type']]})")
    
    print(f"\nStart Position: {scenario['start_positions']}")
    print(f"Start Direction: {scenario['start_directions']}")
    print(f"Goals: {scenario['goals']}")
    print(f"True Goal: {scenario['goal']}")
    
    print(f"\nTrajectory Length: {len(scenario['all_actions'])} steps")
    print(f"Actions: {[int(a) for a in scenario['all_actions'][:10]]}{'...' if len(scenario['all_actions']) > 10 else ''}")
    
    # Show position changes
    print(f"\nPosition Trajectory (first 5 steps):")
    for i, obs in enumerate(scenario['all_obs'][:5]):
        print(f"  Step {i}: pos={obs['target_pos']}, dir={obs['target_dir']}")
    if len(scenario['all_obs']) > 5:
        print(f"  ... ({len(scenario['all_obs']) - 5} more steps)")


def create_trajectory_animation(images, output_path='trajectory.gif', fps=2):
    """
    Create an animated GIF from trajectory images.
    
    Args:
        images: List of rendered images
        output_path: Path to save the GIF
        fps: Frames per second
    """
    import imageio
    
    print(f"Creating animation with {len(images)} frames...")
    imageio.mimsave(output_path, images, fps=fps)
    print(f"✅ Animation saved to {output_path}")


def visualize_trajectory_grid(scenario, save_path=None):
    """
    Create a grid visualization showing the trajectory path on the base grid.
    
    Args:
        scenario: A scenario dict from the dataset
        save_path: Optional path to save the figure
    """
    fig, ax = plt.subplots(figsize=(10, 10))
    
    # Plot base grid (walls)
    grid = scenario['base_grid']
    ax.imshow(grid.T, cmap='gray_r', origin='lower', alpha=0.3)
    
    # Plot goals
    goals = scenario['goals']
    for i, goal in enumerate(goals):
        color = 'red' if goal == scenario['goal'] else 'blue'
        marker = '*' if goal == scenario['goal'] else 'o'
        ax.plot(goal[0], goal[1], marker=marker, markersize=20, color=color, 
                label=f'{"True Goal" if goal == scenario["goal"] else f"Decoy {i}"}')
    
    # Plot trajectory
    positions = [obs['target_pos'] for obs in scenario['all_obs']]
    positions = [(scenario['start_positions'][0], scenario['start_positions'][1])] + positions
    
    x_coords = [pos[0] for pos in positions]
    y_coords = [pos[1] for pos in positions]
    
    # Draw trajectory path
    ax.plot(x_coords, y_coords, 'g-', linewidth=2, alpha=0.7, label='Trajectory')
    
    # Mark start position
    ax.plot(x_coords[0], y_coords[0], 'go', markersize=15, label='Start')
    
    # Add step numbers
    for i in range(0, len(positions), max(1, len(positions)//10)):
        ax.text(x_coords[i], y_coords[i], str(i), fontsize=8, 
                bbox=dict(boxstyle='round', facecolor='white', alpha=0.7))
    
    ax.set_xlim(-0.5, scenario['size'] - 0.5)
    ax.set_ylim(-0.5, scenario['size'] - 0.5)
    ax.set_xlabel('X')
    ax.set_ylabel('Y')
    ax.set_title(f"Trajectory Visualization (Size: {scenario['size']}, Style: {scenario['hidden_cost_type']})")
    ax.legend()
    ax.grid(True, alpha=0.3)
    
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
        print(f"✅ Trajectory visualization saved to {save_path}")
    else:
        plt.show()
    
    plt.close()


def example_1_basic_loading():
    """Example 1: Basic dataset loading and inspection."""
    print("\n" + "="*60)
    print("EXAMPLE 1: Basic Loading and Inspection")
    print("="*60)
    
    # Load dataset
    results = load_dataset('results.pkl.gz')
    
    # Inspect first scenario
    scenario = results[0]
    display_trajectory_summary(scenario)
    
    # Show dataset statistics
    print("\n" + "="*60)
    print("DATASET STATISTICS")
    print("="*60)
    print(f"Total scenarios: {len(results)}")
    
    sizes = [r['size'] for r in results]
    print(f"Grid sizes: {sorted(set(sizes))}")
    
    cost_types = [r['hidden_cost_type'] for r in results]
    style_names = ["like_wall", "hate_wall", "like_edge", "hate_edge"]
    print(f"\nScenarios by behavior style:")
    for cost_type in sorted(set(cost_types)):
        count = cost_types.count(cost_type)
        print(f"  {style_names[cost_type]}: {count}")
    
    trajectory_lengths = [len(r['all_actions']) for r in results]
    print(f"\nTrajectory lengths:")
    print(f"  Average: {np.mean(trajectory_lengths):.1f} steps")
    print(f"  Min/Max: {min(trajectory_lengths)}/{max(trajectory_lengths)} steps")


def example_2_render_single_trajectory():
    """Example 2: Render images for a single trajectory."""
    print("\n" + "="*60)
    print("EXAMPLE 2: Rendering Single Trajectory")
    print("="*60)
    
    # Load dataset
    results = load_dataset('results.pkl.gz')
    
    # Select a scenario
    scenario = results[0]
    display_trajectory_summary(scenario)
    
    # Render all images (without saving)
    images = render_trajectory_images(scenario, tile_size=32)
    
    # Display first and last frame
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    axes[0].imshow(images[0])
    axes[0].set_title('First Frame')
    axes[0].axis('off')
    
    axes[1].imshow(images[-1])
    axes[1].set_title('Last Frame')
    axes[1].axis('off')
    
    plt.tight_layout()
    plt.savefig('trajectory_first_last.png', dpi=150)
    print("✅ Saved first and last frames to trajectory_first_last.png")
    plt.close()


def example_3_create_animation():
    """Example 3: Create animated GIF from trajectory."""
    print("\n" + "="*60)
    print("EXAMPLE 3: Creating Animated GIF")
    print("="*60)
    
    # Load dataset
    results = load_dataset('results.pkl.gz')
    
    # Select a scenario with reasonable length
    scenario = next((s for s in results if 10 <= len(s['all_actions']) <= 30), results[0])
    display_trajectory_summary(scenario)
    
    # Render images
    images = render_trajectory_images(scenario, tile_size=32)
    
    # Create animation
    create_trajectory_animation(images, output_path='trajectory_animation.gif', fps=2)


def example_4_visualize_path():
    """Example 4: Visualize trajectory path on grid."""
    print("\n" + "="*60)
    print("EXAMPLE 4: Trajectory Path Visualization")
    print("="*60)
    
    # Load dataset
    results = load_dataset('results.pkl.gz')
    
    # Visualize different behavior styles
    style_names = ["like_wall", "hate_wall", "like_edge", "hate_edge"]
    
    for style_id in range(4):
        # Find a scenario with this style
        scenario = next((s for s in results if s['hidden_cost_type'] == style_id), None)
        if scenario:
            print(f"\nVisualizing {style_names[style_id]} trajectory...")
            visualize_trajectory_grid(scenario, save_path=f'trajectory_{style_names[style_id]}.png')


def example_5_compare_behaviors():
    """Example 5: Compare different behavior styles on same layout."""
    print("\n" + "="*60)
    print("EXAMPLE 5: Comparing Behavior Styles")
    print("="*60)
    
    # Load dataset
    results = load_dataset('results.pkl.gz')
    
    # Find scenarios with same layout but different styles
    # Group by (size, layout_id, scenario_id)
    from collections import defaultdict
    grouped = defaultdict(list)
    
    for scenario in results:
        key = (scenario['size'], scenario['layout_id'], scenario['scenario_id'])
        grouped[key].append(scenario)
    
    # Find a group with all 4 styles
    for key, scenarios in grouped.items():
        if len(scenarios) == 4:
            print(f"\nFound complete set: Size={key[0]}, Layout={key[1]}, Scenario={key[2]}")
            
            # Create comparison plot
            fig, axes = plt.subplots(2, 2, figsize=(16, 16))
            axes = axes.flatten()
            
            style_names = ["like_wall", "hate_wall", "like_edge", "hate_edge"]
            
            for i, scenario in enumerate(sorted(scenarios, key=lambda s: s['hidden_cost_type'])):
                ax = axes[i]
                
                # Plot base grid
                grid = scenario['base_grid']
                ax.imshow(grid.T, cmap='gray_r', origin='lower', alpha=0.3)
                
                # Plot goals
                for goal in scenario['goals']:
                    color = 'red' if goal == scenario['goal'] else 'blue'
                    marker = '*' if goal == scenario['goal'] else 'o'
                    ax.plot(goal[0], goal[1], marker=marker, markersize=15, color=color)
                
                # Plot trajectory
                positions = [obs['target_pos'] for obs in scenario['all_obs']]
                positions = [(scenario['start_positions'][0], scenario['start_positions'][1])] + positions
                
                x_coords = [pos[0] for pos in positions]
                y_coords = [pos[1] for pos in positions]
                
                ax.plot(x_coords, y_coords, 'g-', linewidth=2, alpha=0.7)
                ax.plot(x_coords[0], y_coords[0], 'go', markersize=12)
                
                ax.set_xlim(-0.5, scenario['size'] - 0.5)
                ax.set_ylim(-0.5, scenario['size'] - 0.5)
                ax.set_title(f"{style_names[scenario['hidden_cost_type']]} ({len(scenario['all_actions'])} steps)")
                ax.grid(True, alpha=0.3)
            
            plt.tight_layout()
            plt.savefig('behavior_comparison.png', dpi=150, bbox_inches='tight')
            print("✅ Behavior comparison saved to behavior_comparison.png")
            plt.close()
            break


if __name__ == "__main__":
    # Run all examples
    # Note: Make sure 'results.pkl.gz' exists in the current directory
    
    print("\n" + "="*60)
    print("DATASET LOADING AND RENDERING EXAMPLES")
    print("="*60)
    
    try:
        # Example 1: Basic loading and inspection
        example_1_basic_loading()
        
        # Example 2: Render single trajectory
        example_2_render_single_trajectory()
        
        # Example 3: Create animation (requires imageio: pip install imageio)
        try:
            example_3_create_animation()
        except ImportError:
            print("\n⚠️  Skipping animation example (requires: pip install imageio)")
        
        # Example 4: Visualize trajectory paths
        example_4_visualize_path()
        
        # Example 5: Compare behavior styles
        example_5_compare_behaviors()
        
        print("\n" + "="*60)
        print("✅ ALL EXAMPLES COMPLETED")
        print("="*60)
        
    except FileNotFoundError:
        print("\n❌ Error: Could not find 'results.pkl.gz'")
        print("Please run generator_working.py first to generate the dataset.")
    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()
