"""
Simplified Main Evaluation Script

This script evaluates observer algorithms on datasets generated by the generator.
"""

import argparse
import numpy as np
import pandas as pd
import json
from typing import Tuple
from time import time

from multigrid.envs.goal_prediction import AGREnv
from multigrid.gr_pursuer.agents.observer import BeliefUpdateObserver
from multigrid.core.actions import Action

def evaluate_scenario(scenario_data, verbose=False):
    """
    Evaluate a single scenario.
    
    Returns:
        Tuple of (success, convergence_step, execution_time)
    """
    try:
        # Parse scenario data
        base_grid = np.array(json.loads(scenario_data['base_grid']))
        hidden_cost = np.array(json.loads(scenario_data['hidden_cost']))
        goals = eval(scenario_data['goals'])
        goal = eval(scenario_data['goal'])
        observer_pos = eval(scenario_data['observer_pos'])
        target_pos = eval(scenario_data['target_pos'])
        observer_dir = scenario_data['observer_dir']
        target_dir = scenario_data['target_dir']
        target_actions = [Action(int(a)) for a in json.loads(scenario_data['all_actions'])]
        
        if verbose:
            print(f"    Target goal: {goal}")
            print(f"    Observer: {observer_pos}, Target: {target_pos}")
            print(f"    Trajectory: {len(target_actions)} steps")
        
        # Setup environment
        env = AGREnv(
            base_grid=base_grid,
            goals=goals,
            goal=goal,
            hidden_cost=hidden_cost,
            enable_hidden_cost=True,
            agents_start_pos=[observer_pos, target_pos],
            agents_start_dir=[observer_dir, target_dir],
            render_mode=None
        )
        
        obs, info = env.reset()
        observer = BeliefUpdateObserver(env)
        
        # Track performance
        success = False
        convergence_step = -1
        first_correct_step = -1  # Track when goal was first correctly identified
        start_time = time()
        
        for step, target_action in enumerate(target_actions):
            # Observer stays still during target trajectory replay to match dataset generation
            # Observer only updates beliefs, doesn't move
            observer_action = 6  # Action.stay - observer remains stationary
            
            # Update observer beliefs based on current observation
            observer.compute_action(obs)  # This updates beliefs without using the returned action
            
            # Step environment with target action and observer staying still
            actions = {0: observer_action, 1: target_action}
            obs, reward, terminated, truncated, info = env.step(actions)
            
            # Check goal prediction
            goal_beliefs = observer.goal_belief
            predicted_goal = max(goal_beliefs.items(), key=lambda x: x[1])
            max_confidence = predicted_goal[1]
            predicted_goal_pos = predicted_goal[0]
            
            # Check for convergence (stable correct prediction)
            if predicted_goal_pos == goal and max_confidence > 0.5:
                # Mark first time we get correct prediction
                if first_correct_step == -1:
                    first_correct_step = observer.step
                    if verbose:
                        print(f"      ✅ Goal first identified at step {first_correct_step} (confidence: {max_confidence:.3f})")
            else:
                # Reset if prediction becomes incorrect after being correct
                if first_correct_step != -1:
                    first_correct_step = -1
                    if verbose:
                        print(f"      ⚠️  Lost correct prediction at step {observer.step}")
            # Continue through entire trajectory
        
        # Final convergence validation - must end with correct prediction and have stable identification
        final_goal_beliefs = observer.goal_belief
        final_predicted_goal = max(final_goal_beliefs.items(), key=lambda x: x[1])
        final_confidence = final_predicted_goal[1]
        final_predicted_goal_pos = final_predicted_goal[0]
        
        # Determine final success based on convergence criteria
        if (final_predicted_goal_pos == goal and final_confidence > 0.5 and first_correct_step != -1):
            success = True
            convergence_step = first_correct_step
            if verbose:
                print(f"      🎯 Converged at step {convergence_step} (final confidence: {final_confidence:.3f})")
        else:
            success = False
            convergence_step = -1
            if verbose:
                if first_correct_step != -1:
                    print(f"      ❌ Lost convergence - identified at step {first_correct_step} but final prediction incorrect")
                else:
                    print(f"      ❌ Never achieved stable correct prediction (final: {final_predicted_goal_pos}, confidence: {final_confidence:.3f})")
        
        execution_time = time() - start_time
        env.close()
        
        return success, convergence_step, execution_time
        
    except Exception as e:
        if verbose:
            print(f"      ❌ Error: {e}")
        return False, -1, 0.0

def main():
    """Main evaluation function."""
    parser = argparse.ArgumentParser(description="Evaluate goal recognition algorithms")
    parser.add_argument("--dataset", type=str, required=True, help="CSV dataset file")
    parser.add_argument("--verbose", action="store_true", help="Detailed output")
    
    args = parser.parse_args()
    
    try:
        print(f"📖 Loading dataset: {args.dataset}")
        df = pd.read_csv(args.dataset)
        print(f"📊 Found {len(df)} scenarios")
        
        if 'behavior_style' in df.columns:
            print(f"   Styles: {list(df['behavior_style'].unique())}")
        
    except Exception as e:
        print(f"❌ Error loading dataset: {e}")
        return
    
    # Evaluation
    results = []
    success_count = 0
    total_convergence_steps = 0
    start_time = time()
    
    print(f"\n🚀 Starting evaluation...")
    
    for idx, row in df.iterrows():
        if args.verbose:
            print(f"\n🔍 Scenario {idx + 1}/{len(df)}")
            if 'behavior_style' in row:
                print(f"   Style: {row['behavior_style']}")
        else:
            print(f"🔍 {idx + 1}/{len(df)}", end=" ")
        
        success, convergence_step, exec_time = evaluate_scenario(row, args.verbose)
        
        results.append({
            'success': success,
            'convergence_step': convergence_step,
            'execution_time': exec_time
        })
        
        if success:
            success_count += 1
            total_convergence_steps += convergence_step
        
        if not args.verbose:
            status = "✅" if success else "❌"
            print(status)
    
    total_time = time() - start_time
    
    # Results summary
    print(f"\n📊 Evaluation Results:")
    print(f"   Total scenarios: {len(df)}")
    print(f"   Successful: {success_count}")
    print(f"   Success rate: {success_count/len(df)*100:.1f}%")
    
    if success_count > 0:
        avg_convergence = total_convergence_steps / success_count
        print(f"   Avg convergence step: {avg_convergence:.1f}")
    
    print(f"   Total time: {total_time:.1f}s")
    
    # Add results to dataframe and save
    for i, result in enumerate(results):
        df.loc[i, 'eval_success'] = result['success']
        df.loc[i, 'eval_convergence_step'] = result['convergence_step']
        df.loc[i, 'eval_execution_time'] = result['execution_time']
    
    output_file = f"evaluation_results_{int(time())}.csv"
    df.to_csv(output_file, index=False)
    print(f"\n💾 Results saved: {output_file}")

if __name__ == "__main__":
    main()