"""
Goal Recognition Experiment Runner

This module evaluates observer algorithms on pre-generated datasets containing:
1. Actor trajectories computed with different behavior styles (hidden costs)
2. Environment layouts and goal configurations 
3. Complete scenario information

The main function:
1. Loads datasets generated by generator.py
2. Replays actor actions while running observer algorithms
3. Evaluates observer performance (goal prediction accuracy and speed)
4. Saves results with success rates and convergence statistics
"""

import argparse
import numpy as np
import pandas as pd
import json
from typing import Dict, List, Tuple, Optional, Any
from time import time

from multigrid.envs.goal_prediction import AGREnv
from multigrid.gr_pursuer.agents.target import AstarTarget
from multigrid.gr_pursuer.agents.observer import BeliefUpdateObserver
from multigrid.core.actions import Action


def run_scenario(scenario_config: Dict[str, Any], verbose: bool = False) -> Tuple[bool, int, Dict[str, Any]]:
    """
    Run a single goal recognition scenario.
    
    Args:
        scenario_config: Dictionary containing all scenario parameters
        verbose: Whether to print detailed progress information
        
    Returns:
        Tuple of (success_flag, convergence_step, detailed_results)
    """
    # Extract configuration
    base_grid = scenario_config['base_grid']
    goals = scenario_config['goals']
    goal = scenario_config['goal']
    hidden_cost = scenario_config['hidden_cost']
    observer_pos = scenario_config['observer_pos']
    target_pos = scenario_config['target_pos']
    observer_dir = scenario_config['observer_dir']
    target_dir = scenario_config['target_dir']
    target_actions = scenario_config['target_actions']
    
    if verbose:
        print(f"    🎯 Target goal: {goal}")
        print(f"    📍 Observer: {observer_pos} (dir {observer_dir})")
        print(f"    🎲 Target: {target_pos} (dir {target_dir})")
        print(f"    📏 Trajectory length: {len(target_actions)} steps")
    
    # Setup environment
    agents_start_pos = [observer_pos, target_pos]
    agents_start_dir = [observer_dir, target_dir]
    
    env = AGREnv(
        base_grid=base_grid,
        goals=goals, 
        goal=goal,
        hidden_cost=hidden_cost,
        enable_hidden_cost=True,
        agents_start_pos=agents_start_pos,
        agents_start_dir=agents_start_dir,
        render_mode=None
    )
    
    observation, info = env.reset()
    
    # Create observer agent (algorithm under test)
    observer_agent = BeliefUpdateObserver(env)
    
    # Track performance metrics
    success = False
    convergence_step = -1
    first_correct_step = -1  # Track when goal was first correctly identified
    goal_belief_history = []
    max_confidence_history = []
    predicted_goals_history = []
    
    step = 0
    start_time = time()
    
    try:
        while not env.unwrapped.is_done() and step < len(target_actions):
            # Observer computes its action based on current beliefs
            observer_action = observer_agent.compute_action(observation)
            
            # Use pre-computed target action from dataset
            target_action = target_actions[step]
            
            # Step environment
            actions = [observer_action, target_action]
            observation, reward, terminated, truncated, info = env.step(actions)
            
            # Analyze current goal beliefs
            goal_beliefs = observer_agent.goal_belief.copy()
            predicted_goal = max(goal_beliefs.items(), key=lambda x: x[1])
            max_confidence = predicted_goal[1]
            predicted_goal_pos = predicted_goal[0]
            
            # Store belief history
            goal_belief_history.append(goal_beliefs)
            max_confidence_history.append(max_confidence)
            predicted_goals_history.append(predicted_goal_pos)
            
            # Check for convergence (stable correct prediction)
            if predicted_goal_pos == goal and max_confidence > 0.5:
                # Mark first time we get correct prediction
                if first_correct_step == -1:
                    first_correct_step = observer_agent.step
                    if verbose:
                        print(f"      ✅ Goal first identified at step {first_correct_step} (confidence: {max_confidence:.3f})")
            else:
                # Reset if prediction becomes incorrect after being correct
                if first_correct_step != -1:
                    first_correct_step = -1
                    if verbose:
                        print(f"      ⚠️  Lost correct prediction at step {observer_agent.step}")
            
            step += 1
            
    except Exception as e:
        print(f"      ❌ Error during scenario execution: {e}")
        return False, -1, {}
    
    finally:
        env.close()
    
    execution_time = time() - start_time
    
    # Final convergence validation - must end with correct prediction and have stable identification
    final_predicted_goal = predicted_goals_history[-1] if predicted_goals_history else None
    final_confidence = max_confidence_history[-1] if max_confidence_history else 0.0
    
    if (final_predicted_goal == goal and final_confidence > 0.5 and first_correct_step != -1):
        success = True
        convergence_step = first_correct_step
        if verbose:
            print(f"      🎯 Converged at step {convergence_step} (final confidence: {final_confidence:.3f})")
    else:
        success = False
        convergence_step = -1
        if verbose:
            if first_correct_step != -1:
                print(f"      ❌ Lost convergence - identified at step {first_correct_step} but final prediction incorrect")
            else:
                print(f"      ❌ Never achieved stable correct prediction")
    
    # Prepare detailed results
    results = {
        'success': success,
        'convergence_step': convergence_step,
        'total_steps': step,
        'execution_time': execution_time,
        'final_confidence': final_confidence,
        'final_predicted_goal': final_predicted_goal,
        'cache_stats': observer_agent.get_cache_stats()
    }
    
    if verbose and success:
        print(f"      📊 Execution time: {execution_time:.3f}s")
        print(f"      💾 Cache hit rate: {results['cache_stats']['hit_rate']:.1%}")
    
    return success, convergence_step, results


def main(dataset_path: Optional[str] = None, verbose: bool = False) -> None:
    """
    Run goal recognition evaluation on a dataset.
    
    Args:
        dataset_path: Path to CSV dataset file
        verbose: Whether to print detailed progress information
    """
    if dataset_path is None:
        print("❌ No dataset specified. Use --dataset to provide a CSV file.")
        return
        
    try:
        print(f"📖 Loading dataset: {dataset_path}")
        scenarios_df = pd.read_csv(dataset_path)
        print(f"📊 Found {len(scenarios_df)} scenarios")
        
        # Display dataset summary
        if 'size' in scenarios_df.columns:
            print(f"   Grid sizes: {sorted(scenarios_df['size'].unique())}")
        if 'hidden_cost_style' in scenarios_df.columns:
            print(f"   Behavior styles: {list(scenarios_df['hidden_cost_style'].unique())}")
        
    except FileNotFoundError:
        print(f"❌ Dataset file not found: {dataset_path}")
        return
    except Exception as e:
        print(f"❌ Error loading dataset: {e}")
        return
    
    # Performance tracking
    success_count = 0
    convergence_step_sum = 0
    total_execution_time = 0
    detailed_results = []
    
    print(f"\n🚀 Starting evaluation...")
    start_time = time()
    
    for idx, scenario_row in scenarios_df.iterrows():
        if verbose:
            print(f"\n🔍 Scenario {idx + 1}/{len(scenarios_df)}")
            if 'hidden_cost_style' in scenario_row:
                print(f"   Style: {scenario_row['hidden_cost_style']}")
            if 'size' in scenario_row:
                print(f"   Size: {scenario_row['size']}x{scenario_row['size']}")
        else:
            print(f"🔍 Scenario {idx + 1}/{len(scenarios_df)}", end=" ")
        
        try:
            # Parse scenario configuration
            scenario_config = {
                'base_grid': np.array(json.loads(scenario_row['base_grid'])),
                'goals': eval(scenario_row['goals']),
                'goal': eval(scenario_row['goal']),
                'hidden_cost': np.array(json.loads(scenario_row['hidden_cost'])),
                'observer_pos': eval(scenario_row['observer_pos']),
                'target_pos': eval(scenario_row['target_pos']),
                'observer_dir': scenario_row['observer_dir'],
                'target_dir': scenario_row['target_dir'],
                'target_actions': [Action(v) for v in json.loads(scenario_row['all_actions'])]
            }
            
            # Run scenario
            success, convergence_step, results = run_scenario(scenario_config, verbose)
            
            # Update statistics
            scenarios_df.loc[idx, 'success'] = success
            scenarios_df.loc[idx, 'convergence_step'] = convergence_step
            scenarios_df.loc[idx, 'execution_time'] = results.get('execution_time', 0)
            scenarios_df.loc[idx, 'final_confidence'] = results.get('final_confidence', 0)
            
            if success:
                success_count += 1
                convergence_step_sum += convergence_step
                
            total_execution_time += results.get('execution_time', 0)
            detailed_results.append(results)
            
            if not verbose:
                status = "✅" if success else "❌"
                print(f"{status}")
            
        except Exception as e:
            print(f"❌ Error processing scenario {idx}: {e}")
            scenarios_df.loc[idx, 'success'] = False
            scenarios_df.loc[idx, 'convergence_step'] = -1
            continue
        
        # Save intermediate results every 10 scenarios
        if (idx + 1) % 10 == 0:
            temp_filename = f"evaluation_results_temp_{idx + 1}.csv"
            scenarios_df.to_csv(temp_filename, index=False)
            if verbose:
                print(f"💾 Saved intermediate results: {temp_filename}")
    
    total_time = time() - start_time
    
    # Calculate and display final statistics
    print(f"\n📊 Evaluation Complete!")
    print(f"   Total scenarios: {len(scenarios_df)}")
    print(f"   Successful predictions: {success_count}")
    print(f"   Success rate: {success_count/len(scenarios_df)*100:.1f}%")
    
    if success_count > 0:
        avg_convergence = convergence_step_sum / success_count
        print(f"   Average convergence step: {avg_convergence:.1f}")
    
    print(f"   Total execution time: {total_time:.1f}s")
    print(f"   Average time per scenario: {total_time/len(scenarios_df):.3f}s")
    
    # Save final results
    output_filename = f"evaluation_results_{int(time())}.csv"
    scenarios_df.to_csv(output_filename, index=False)
    print(f"\n💾 Final results saved: {output_filename}")
    
    # Summary by behavior style (if available)
    if 'hidden_cost_style' in scenarios_df.columns:
        print(f"\n📈 Results by Behavior Style:")
        style_summary = scenarios_df.groupby('hidden_cost_style').agg({
            'success': ['count', 'sum', 'mean'],
            'convergence_step': 'mean'
        }).round(2)
        print(style_summary)
      
if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Evaluate goal recognition algorithms on generated datasets",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python main.py --dataset goal_recognition_dataset.csv
  python main.py --dataset results.csv --verbose
        """
    )
    
    parser.add_argument(
        "--dataset", 
        type=str, 
        required=True,
        help="Path to CSV dataset file generated by generator.py"
    )
    
    parser.add_argument(
        "--verbose", 
        action="store_true",
        help="Print detailed progress information"
    )
    
    args = parser.parse_args()
    main(args.dataset, args.verbose)